/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.10.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *tab;
    QGroupBox *groupBox_drive;
    QLabel *lb_drive_mode;
    QLabel *lb_drive_control_mode;
    QLabel *lb_drive_input_mode;
    QTextEdit *tx_drive_mode;
    QTextEdit *tx_drive_control_mode;
    QTextEdit *tx_drive_input_mode;
    QPushButton *bt_drive_mode_manual;
    QPushButton *bt_drive_mode_program;
    QPushButton *bt_drive_control_mode_velocity;
    QPushButton *bt_drive_control_mode_stroke;
    QPushButton *bt_drive_input_mode_direct;
    QPushButton *bt_drive_input_mode_autoware;
    QGroupBox *gb_velocity;
    QSpinBox *spin_velocity_input;
    QSlider *hS_velocity_input;
    QLabel *lb_velocity_target;
    QTextEdit *tx_velocity_target;
    QTextEdit *tx_velocity_actual;
    QLabel *lb_velocity_actual;
    QGroupBox *gb_stroke;
    QSpinBox *spin_stroke_input;
    QSlider *hS_stroke_input;
    QLabel *lb_stroke_target;
    QTextEdit *tx_stroke_target;
    QTextEdit *tx_stroke_actual;
    QLabel *lb_stroke_actual;
    QGroupBox *gb_shift;
    QPushButton *bt_shift_P;
    QPushButton *bt_shift_R;
    QPushButton *bt_shift_D;
    QPushButton *bt_shift_N;
    QPushButton *bt_shift_4;
    QPushButton *bt_shift_2L;
    QGroupBox *groupBox_steer;
    QLabel *lb_steer_mode;
    QLabel *lb_steer_input_mode;
    QTextEdit *tx_steer_mode;
    QTextEdit *tx_steer_input_mode;
    QPushButton *bt_steer_mode_manual;
    QPushButton *bt_steer_mode_program;
    QPushButton *bt_steer_input_mode_direct;
    QPushButton *bt_steer_input_mode_autoware;
    QGroupBox *gb_angle;
    QSpinBox *spin_angle_input;
    QSlider *hS_angle_input;
    QLabel *lb_angle_target;
    QTextEdit *tx_angle_target;
    QTextEdit *tx_angle_actual;
    QLabel *lb_angle_actual;
    QGroupBox *groupBox_other;
    QLabel *lb_blinker_right;
    QPushButton *bt_blinker_right_on;
    QPushButton *bt_blinker_right_off;
    QLabel *lb_blinker_left;
    QPushButton *bt_blinker_left_on;
    QPushButton *bt_blinker_left_off;
    QWidget *tab_2;
    QPushButton *bt_emergency_clear;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(826, 716);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(10, 30, 801, 621));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        groupBox_drive = new QGroupBox(tab);
        groupBox_drive->setObjectName(QStringLiteral("groupBox_drive"));
        groupBox_drive->setEnabled(true);
        groupBox_drive->setGeometry(QRect(10, 10, 331, 501));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        QBrush brush1(QColor(238, 238, 236, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        groupBox_drive->setPalette(palette);
        groupBox_drive->setAutoFillBackground(true);
        lb_drive_mode = new QLabel(groupBox_drive);
        lb_drive_mode->setObjectName(QStringLiteral("lb_drive_mode"));
        lb_drive_mode->setGeometry(QRect(10, 40, 91, 17));
        lb_drive_control_mode = new QLabel(groupBox_drive);
        lb_drive_control_mode->setObjectName(QStringLiteral("lb_drive_control_mode"));
        lb_drive_control_mode->setGeometry(QRect(10, 80, 101, 16));
        lb_drive_input_mode = new QLabel(groupBox_drive);
        lb_drive_input_mode->setObjectName(QStringLiteral("lb_drive_input_mode"));
        lb_drive_input_mode->setGeometry(QRect(10, 110, 101, 17));
        tx_drive_mode = new QTextEdit(groupBox_drive);
        tx_drive_mode->setObjectName(QStringLiteral("tx_drive_mode"));
        tx_drive_mode->setGeometry(QRect(60, 30, 121, 41));
        tx_drive_mode->setAutoFillBackground(true);
        tx_drive_mode->setLineWidth(0);
        tx_drive_mode->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_drive_mode->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_drive_mode->setReadOnly(true);
        tx_drive_mode->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_drive_control_mode = new QTextEdit(groupBox_drive);
        tx_drive_control_mode->setObjectName(QStringLiteral("tx_drive_control_mode"));
        tx_drive_control_mode->setGeometry(QRect(110, 80, 71, 21));
        tx_drive_control_mode->setLineWidth(0);
        tx_drive_control_mode->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_drive_control_mode->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_drive_control_mode->setReadOnly(true);
        tx_drive_input_mode = new QTextEdit(groupBox_drive);
        tx_drive_input_mode->setObjectName(QStringLiteral("tx_drive_input_mode"));
        tx_drive_input_mode->setGeometry(QRect(110, 110, 71, 21));
        tx_drive_input_mode->setLineWidth(0);
        tx_drive_input_mode->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_drive_input_mode->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_drive_input_mode->setReadOnly(true);
        bt_drive_mode_manual = new QPushButton(groupBox_drive);
        bt_drive_mode_manual->setObjectName(QStringLiteral("bt_drive_mode_manual"));
        bt_drive_mode_manual->setEnabled(false);
        bt_drive_mode_manual->setGeometry(QRect(190, 40, 61, 25));
        bt_drive_mode_program = new QPushButton(groupBox_drive);
        bt_drive_mode_program->setObjectName(QStringLiteral("bt_drive_mode_program"));
        bt_drive_mode_program->setEnabled(false);
        bt_drive_mode_program->setGeometry(QRect(260, 40, 61, 25));
        bt_drive_control_mode_velocity = new QPushButton(groupBox_drive);
        bt_drive_control_mode_velocity->setObjectName(QStringLiteral("bt_drive_control_mode_velocity"));
        bt_drive_control_mode_velocity->setEnabled(false);
        bt_drive_control_mode_velocity->setGeometry(QRect(190, 80, 61, 25));
        bt_drive_control_mode_stroke = new QPushButton(groupBox_drive);
        bt_drive_control_mode_stroke->setObjectName(QStringLiteral("bt_drive_control_mode_stroke"));
        bt_drive_control_mode_stroke->setEnabled(false);
        bt_drive_control_mode_stroke->setGeometry(QRect(260, 80, 61, 25));
        bt_drive_input_mode_direct = new QPushButton(groupBox_drive);
        bt_drive_input_mode_direct->setObjectName(QStringLiteral("bt_drive_input_mode_direct"));
        bt_drive_input_mode_direct->setEnabled(false);
        bt_drive_input_mode_direct->setGeometry(QRect(190, 110, 61, 25));
        bt_drive_input_mode_autoware = new QPushButton(groupBox_drive);
        bt_drive_input_mode_autoware->setObjectName(QStringLiteral("bt_drive_input_mode_autoware"));
        bt_drive_input_mode_autoware->setEnabled(false);
        bt_drive_input_mode_autoware->setGeometry(QRect(260, 110, 61, 25));
        gb_velocity = new QGroupBox(groupBox_drive);
        gb_velocity->setObjectName(QStringLiteral("gb_velocity"));
        gb_velocity->setEnabled(false);
        gb_velocity->setGeometry(QRect(10, 140, 311, 91));
        QPalette palette1;
        QBrush brush2(QColor(0, 0, 0, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        QBrush brush3(QColor(186, 189, 182, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush);
        QBrush brush4(QColor(220, 222, 218, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        QBrush brush5(QColor(93, 94, 91, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush5);
        QBrush brush6(QColor(124, 126, 121, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        QBrush brush7(QColor(255, 255, 220, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        QBrush brush8(QColor(0, 0, 0, 128));
        brush8.setStyle(Qt::SolidPattern);
		//palette1.setBrush(QPalette::Active, QPalette::PlaceholderText, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
		//palette1.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
		//palette1.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush8);
        gb_velocity->setPalette(palette1);
        gb_velocity->setContextMenuPolicy(Qt::DefaultContextMenu);
        gb_velocity->setAcceptDrops(false);
        gb_velocity->setAutoFillBackground(true);
        gb_velocity->setFlat(false);
        gb_velocity->setCheckable(false);
        spin_velocity_input = new QSpinBox(gb_velocity);
        spin_velocity_input->setObjectName(QStringLiteral("spin_velocity_input"));
        spin_velocity_input->setGeometry(QRect(60, 30, 61, 26));
        hS_velocity_input = new QSlider(gb_velocity);
        hS_velocity_input->setObjectName(QStringLiteral("hS_velocity_input"));
        hS_velocity_input->setGeometry(QRect(10, 70, 160, 16));
        hS_velocity_input->setOrientation(Qt::Horizontal);
        lb_velocity_target = new QLabel(gb_velocity);
        lb_velocity_target->setObjectName(QStringLiteral("lb_velocity_target"));
        lb_velocity_target->setGeometry(QRect(180, 30, 101, 17));
        tx_velocity_target = new QTextEdit(gb_velocity);
        tx_velocity_target->setObjectName(QStringLiteral("tx_velocity_target"));
        tx_velocity_target->setGeometry(QRect(230, 30, 71, 21));
        tx_velocity_target->setLineWidth(0);
        tx_velocity_target->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_velocity_target->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_velocity_target->setReadOnly(true);
        tx_velocity_target->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_velocity_actual = new QTextEdit(gb_velocity);
        tx_velocity_actual->setObjectName(QStringLiteral("tx_velocity_actual"));
        tx_velocity_actual->setGeometry(QRect(230, 60, 71, 21));
        tx_velocity_actual->setLineWidth(0);
        tx_velocity_actual->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_velocity_actual->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_velocity_actual->setReadOnly(true);
        tx_velocity_actual->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_velocity_actual = new QLabel(gb_velocity);
        lb_velocity_actual->setObjectName(QStringLiteral("lb_velocity_actual"));
        lb_velocity_actual->setGeometry(QRect(180, 60, 101, 17));
        gb_stroke = new QGroupBox(groupBox_drive);
        gb_stroke->setObjectName(QStringLiteral("gb_stroke"));
        gb_stroke->setEnabled(false);
        gb_stroke->setGeometry(QRect(10, 240, 311, 91));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
		//palette2.setBrush(QPalette::Active, QPalette::PlaceholderText, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
		//palette2.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
		//palette2.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush8);
        gb_stroke->setPalette(palette2);
        gb_stroke->setContextMenuPolicy(Qt::DefaultContextMenu);
        gb_stroke->setAcceptDrops(false);
        gb_stroke->setAutoFillBackground(true);
        gb_stroke->setFlat(false);
        gb_stroke->setCheckable(false);
        spin_stroke_input = new QSpinBox(gb_stroke);
        spin_stroke_input->setObjectName(QStringLiteral("spin_stroke_input"));
        spin_stroke_input->setGeometry(QRect(60, 30, 61, 26));
        hS_stroke_input = new QSlider(gb_stroke);
        hS_stroke_input->setObjectName(QStringLiteral("hS_stroke_input"));
        hS_stroke_input->setGeometry(QRect(10, 70, 160, 16));
        hS_stroke_input->setOrientation(Qt::Horizontal);
        lb_stroke_target = new QLabel(gb_stroke);
        lb_stroke_target->setObjectName(QStringLiteral("lb_stroke_target"));
        lb_stroke_target->setGeometry(QRect(180, 30, 101, 17));
        tx_stroke_target = new QTextEdit(gb_stroke);
        tx_stroke_target->setObjectName(QStringLiteral("tx_stroke_target"));
        tx_stroke_target->setGeometry(QRect(230, 30, 71, 21));
        tx_stroke_target->setLineWidth(0);
        tx_stroke_target->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_stroke_target->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_stroke_target->setReadOnly(true);
        tx_stroke_target->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_stroke_actual = new QTextEdit(gb_stroke);
        tx_stroke_actual->setObjectName(QStringLiteral("tx_stroke_actual"));
        tx_stroke_actual->setGeometry(QRect(230, 60, 71, 21));
        tx_stroke_actual->setLineWidth(0);
        tx_stroke_actual->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_stroke_actual->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_stroke_actual->setReadOnly(true);
        tx_stroke_actual->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_stroke_actual = new QLabel(gb_stroke);
        lb_stroke_actual->setObjectName(QStringLiteral("lb_stroke_actual"));
        lb_stroke_actual->setGeometry(QRect(180, 60, 101, 17));
        gb_shift = new QGroupBox(groupBox_drive);
        gb_shift->setObjectName(QStringLiteral("gb_shift"));
        gb_shift->setEnabled(false);
        gb_shift->setGeometry(QRect(10, 340, 311, 151));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
		//palette3.setBrush(QPalette::Active, QPalette::PlaceholderText, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
		//palette3.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
		//palette3.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush8);
        gb_shift->setPalette(palette3);
        gb_shift->setContextMenuPolicy(Qt::DefaultContextMenu);
        gb_shift->setAcceptDrops(false);
        gb_shift->setAutoFillBackground(true);
        gb_shift->setFlat(false);
        gb_shift->setCheckable(false);
        bt_shift_P = new QPushButton(gb_shift);
        bt_shift_P->setObjectName(QStringLiteral("bt_shift_P"));
        bt_shift_P->setEnabled(false);
        bt_shift_P->setGeometry(QRect(40, 30, 51, 51));
        QFont font;
        font.setPointSize(18);
        bt_shift_P->setFont(font);
        bt_shift_R = new QPushButton(gb_shift);
        bt_shift_R->setObjectName(QStringLiteral("bt_shift_R"));
        bt_shift_R->setEnabled(false);
        bt_shift_R->setGeometry(QRect(100, 30, 51, 51));
        bt_shift_R->setFont(font);
        bt_shift_D = new QPushButton(gb_shift);
        bt_shift_D->setObjectName(QStringLiteral("bt_shift_D"));
        bt_shift_D->setGeometry(QRect(220, 30, 51, 51));
        bt_shift_D->setFont(font);
        bt_shift_N = new QPushButton(gb_shift);
        bt_shift_N->setObjectName(QStringLiteral("bt_shift_N"));
        bt_shift_N->setGeometry(QRect(160, 30, 51, 51));
        bt_shift_N->setFont(font);
        bt_shift_4 = new QPushButton(gb_shift);
        bt_shift_4->setObjectName(QStringLiteral("bt_shift_4"));
        bt_shift_4->setGeometry(QRect(100, 90, 51, 51));
        bt_shift_4->setFont(font);
        bt_shift_2L = new QPushButton(gb_shift);
        bt_shift_2L->setObjectName(QStringLiteral("bt_shift_2L"));
        bt_shift_2L->setGeometry(QRect(160, 90, 51, 51));
        bt_shift_2L->setFont(font);
        groupBox_steer = new QGroupBox(tab);
        groupBox_steer->setObjectName(QStringLiteral("groupBox_steer"));
        groupBox_steer->setEnabled(true);
        groupBox_steer->setGeometry(QRect(350, 10, 331, 211));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        groupBox_steer->setPalette(palette4);
        groupBox_steer->setAutoFillBackground(true);
        lb_steer_mode = new QLabel(groupBox_steer);
        lb_steer_mode->setObjectName(QStringLiteral("lb_steer_mode"));
        lb_steer_mode->setGeometry(QRect(10, 40, 91, 17));
        lb_steer_input_mode = new QLabel(groupBox_steer);
        lb_steer_input_mode->setObjectName(QStringLiteral("lb_steer_input_mode"));
        lb_steer_input_mode->setGeometry(QRect(10, 80, 101, 17));
        tx_steer_mode = new QTextEdit(groupBox_steer);
        tx_steer_mode->setObjectName(QStringLiteral("tx_steer_mode"));
        tx_steer_mode->setGeometry(QRect(60, 30, 121, 41));
        tx_steer_mode->setAutoFillBackground(true);
        tx_steer_mode->setLineWidth(0);
        tx_steer_mode->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_steer_mode->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_steer_mode->setReadOnly(true);
        tx_steer_mode->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_steer_input_mode = new QTextEdit(groupBox_steer);
        tx_steer_input_mode->setObjectName(QStringLiteral("tx_steer_input_mode"));
        tx_steer_input_mode->setGeometry(QRect(110, 80, 71, 21));
        tx_steer_input_mode->setLineWidth(0);
        tx_steer_input_mode->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_steer_input_mode->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_steer_input_mode->setReadOnly(true);
        bt_steer_mode_manual = new QPushButton(groupBox_steer);
        bt_steer_mode_manual->setObjectName(QStringLiteral("bt_steer_mode_manual"));
        bt_steer_mode_manual->setEnabled(false);
        bt_steer_mode_manual->setGeometry(QRect(190, 40, 61, 25));
        bt_steer_mode_program = new QPushButton(groupBox_steer);
        bt_steer_mode_program->setObjectName(QStringLiteral("bt_steer_mode_program"));
        bt_steer_mode_program->setEnabled(false);
        bt_steer_mode_program->setGeometry(QRect(260, 40, 61, 25));
        bt_steer_input_mode_direct = new QPushButton(groupBox_steer);
        bt_steer_input_mode_direct->setObjectName(QStringLiteral("bt_steer_input_mode_direct"));
        bt_steer_input_mode_direct->setEnabled(false);
        bt_steer_input_mode_direct->setGeometry(QRect(190, 80, 61, 25));
        bt_steer_input_mode_autoware = new QPushButton(groupBox_steer);
        bt_steer_input_mode_autoware->setObjectName(QStringLiteral("bt_steer_input_mode_autoware"));
        bt_steer_input_mode_autoware->setEnabled(false);
        bt_steer_input_mode_autoware->setGeometry(QRect(260, 80, 61, 25));
        gb_angle = new QGroupBox(groupBox_steer);
        gb_angle->setObjectName(QStringLiteral("gb_angle"));
        gb_angle->setEnabled(false);
        gb_angle->setGeometry(QRect(10, 110, 311, 91));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
		//palette5.setBrush(QPalette::Active, QPalette::PlaceholderText, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
		//palette5.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
		//palette5.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush8);
        gb_angle->setPalette(palette5);
        gb_angle->setContextMenuPolicy(Qt::DefaultContextMenu);
        gb_angle->setAcceptDrops(false);
        gb_angle->setAutoFillBackground(true);
        gb_angle->setFlat(false);
        gb_angle->setCheckable(false);
        spin_angle_input = new QSpinBox(gb_angle);
        spin_angle_input->setObjectName(QStringLiteral("spin_angle_input"));
        spin_angle_input->setGeometry(QRect(60, 30, 61, 26));
        hS_angle_input = new QSlider(gb_angle);
        hS_angle_input->setObjectName(QStringLiteral("hS_angle_input"));
        hS_angle_input->setGeometry(QRect(10, 70, 160, 16));
        hS_angle_input->setOrientation(Qt::Horizontal);
        lb_angle_target = new QLabel(gb_angle);
        lb_angle_target->setObjectName(QStringLiteral("lb_angle_target"));
        lb_angle_target->setGeometry(QRect(180, 30, 101, 17));
        tx_angle_target = new QTextEdit(gb_angle);
        tx_angle_target->setObjectName(QStringLiteral("tx_angle_target"));
        tx_angle_target->setGeometry(QRect(230, 30, 71, 21));
        tx_angle_target->setLineWidth(0);
        tx_angle_target->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_angle_target->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_angle_target->setReadOnly(true);
        tx_angle_target->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_angle_actual = new QTextEdit(gb_angle);
        tx_angle_actual->setObjectName(QStringLiteral("tx_angle_actual"));
        tx_angle_actual->setGeometry(QRect(230, 60, 71, 21));
        tx_angle_actual->setLineWidth(0);
        tx_angle_actual->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_angle_actual->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_angle_actual->setReadOnly(true);
        tx_angle_actual->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_angle_actual = new QLabel(gb_angle);
        lb_angle_actual->setObjectName(QStringLiteral("lb_angle_actual"));
        lb_angle_actual->setGeometry(QRect(180, 60, 101, 17));
        groupBox_other = new QGroupBox(tab);
        groupBox_other->setObjectName(QStringLiteral("groupBox_other"));
        groupBox_other->setEnabled(true);
        groupBox_other->setGeometry(QRect(350, 230, 331, 251));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::Base, brush);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        groupBox_other->setPalette(palette6);
        groupBox_other->setAutoFillBackground(true);
        lb_blinker_right = new QLabel(groupBox_other);
        lb_blinker_right->setObjectName(QStringLiteral("lb_blinker_right"));
        lb_blinker_right->setGeometry(QRect(10, 30, 91, 17));
        bt_blinker_right_on = new QPushButton(groupBox_other);
        bt_blinker_right_on->setObjectName(QStringLiteral("bt_blinker_right_on"));
        bt_blinker_right_on->setEnabled(false);
        bt_blinker_right_on->setGeometry(QRect(110, 30, 61, 25));
        bt_blinker_right_off = new QPushButton(groupBox_other);
        bt_blinker_right_off->setObjectName(QStringLiteral("bt_blinker_right_off"));
        bt_blinker_right_off->setEnabled(false);
        bt_blinker_right_off->setGeometry(QRect(180, 30, 61, 25));
        lb_blinker_left = new QLabel(groupBox_other);
        lb_blinker_left->setObjectName(QStringLiteral("lb_blinker_left"));
        lb_blinker_left->setGeometry(QRect(10, 60, 91, 17));
        bt_blinker_left_on = new QPushButton(groupBox_other);
        bt_blinker_left_on->setObjectName(QStringLiteral("bt_blinker_left_on"));
        bt_blinker_left_on->setEnabled(false);
        bt_blinker_left_on->setGeometry(QRect(110, 60, 61, 25));
        bt_blinker_left_off = new QPushButton(groupBox_other);
        bt_blinker_left_off->setObjectName(QStringLiteral("bt_blinker_left_off"));
        bt_blinker_left_off->setEnabled(false);
        bt_blinker_left_off->setGeometry(QRect(180, 60, 61, 25));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        tabWidget->addTab(tab_2, QString());
        bt_emergency_clear = new QPushButton(centralWidget);
        bt_emergency_clear->setObjectName(QStringLiteral("bt_emergency_clear"));
        bt_emergency_clear->setGeometry(QRect(10, 0, 101, 25));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 826, 28));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        groupBox_drive->setTitle(QApplication::translate("MainWindow", "DRIVE_INFOMATION", nullptr));
        lb_drive_mode->setText(QApplication::translate("MainWindow", "mode", nullptr));
        lb_drive_control_mode->setText(QApplication::translate("MainWindow", "control_mode", nullptr));
        lb_drive_input_mode->setText(QApplication::translate("MainWindow", "input mode", nullptr));
        bt_drive_mode_manual->setText(QApplication::translate("MainWindow", "manual", nullptr));
        bt_drive_mode_program->setText(QApplication::translate("MainWindow", "program", nullptr));
        bt_drive_control_mode_velocity->setText(QApplication::translate("MainWindow", "velocity", nullptr));
        bt_drive_control_mode_stroke->setText(QApplication::translate("MainWindow", "stroke", nullptr));
        bt_drive_input_mode_direct->setText(QApplication::translate("MainWindow", "direct", nullptr));
        bt_drive_input_mode_autoware->setText(QApplication::translate("MainWindow", "auto", nullptr));
        gb_velocity->setTitle(QApplication::translate("MainWindow", "Velocity", nullptr));
        lb_velocity_target->setText(QApplication::translate("MainWindow", "target", nullptr));
        lb_velocity_actual->setText(QApplication::translate("MainWindow", "actual", nullptr));
        gb_stroke->setTitle(QApplication::translate("MainWindow", "Stroke", nullptr));
        lb_stroke_target->setText(QApplication::translate("MainWindow", "target", nullptr));
        lb_stroke_actual->setText(QApplication::translate("MainWindow", "actual", nullptr));
        gb_shift->setTitle(QApplication::translate("MainWindow", "Shift", nullptr));
        bt_shift_P->setText(QApplication::translate("MainWindow", "P", nullptr));
        bt_shift_R->setText(QApplication::translate("MainWindow", "R", nullptr));
        bt_shift_D->setText(QApplication::translate("MainWindow", "D", nullptr));
        bt_shift_N->setText(QApplication::translate("MainWindow", "N", nullptr));
        bt_shift_4->setText(QApplication::translate("MainWindow", "4", nullptr));
        bt_shift_2L->setText(QApplication::translate("MainWindow", "2/L", nullptr));
        groupBox_steer->setTitle(QApplication::translate("MainWindow", "STEER_INFOMATION", nullptr));
        lb_steer_mode->setText(QApplication::translate("MainWindow", "mode", nullptr));
        lb_steer_input_mode->setText(QApplication::translate("MainWindow", "input mode", nullptr));
        bt_steer_mode_manual->setText(QApplication::translate("MainWindow", "manual", nullptr));
        bt_steer_mode_program->setText(QApplication::translate("MainWindow", "program", nullptr));
        bt_steer_input_mode_direct->setText(QApplication::translate("MainWindow", "direct", nullptr));
        bt_steer_input_mode_autoware->setText(QApplication::translate("MainWindow", "auto", nullptr));
        gb_angle->setTitle(QApplication::translate("MainWindow", "Velocity", nullptr));
        lb_angle_target->setText(QApplication::translate("MainWindow", "target", nullptr));
        lb_angle_actual->setText(QApplication::translate("MainWindow", "actual", nullptr));
        groupBox_other->setTitle(QApplication::translate("MainWindow", "OTHER_INFOMATION", nullptr));
        lb_blinker_right->setText(QApplication::translate("MainWindow", "blinker_right", nullptr));
        bt_blinker_right_on->setText(QApplication::translate("MainWindow", "ON", nullptr));
        bt_blinker_right_off->setText(QApplication::translate("MainWindow", "OFF", nullptr));
        lb_blinker_left->setText(QApplication::translate("MainWindow", "blinker_left", nullptr));
        bt_blinker_left_on->setText(QApplication::translate("MainWindow", "ON", nullptr));
        bt_blinker_left_off->setText(QApplication::translate("MainWindow", "OFF", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Tab 1", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "Tab 2", nullptr));
        bt_emergency_clear->setText(QApplication::translate("MainWindow", "\345\256\211\345\205\250\346\251\237\350\203\275\350\247\243\351\231\244", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
